services:
  inicie-backend:
    build:
      context: ./inicie-backend-exam
      dockerfile: Dockerfile
    container_name: inicie-backend
    working_dir: /var/www/html
    volumes:
      - ./inicie-backend-exam:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db
    networks:
      - inicie-network

  inicie-frontend:
    build:
      context: ./inicie-frontend-exam
      dockerfile: Dockerfile
    container_name: inicie-frontend
    volumes:
      - ./inicie-frontend-exam:/app
    ports:
      - "4200:4200"
    depends_on:
      - inicie-backend
    networks:
      - inicie-network

  db:
    image: mysql:8.0
    container_name: inicie-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=inicie-@pp-4561327
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inicie-network

  nginx:
    image: nginx:latest
    container_name: inicie-nginx
    ports:
      - "8080:80"
    volumes:
      - ./inicie-backend-exam:/var/www/html
      - ./inicie-frontend-exam:/app
      - ./inicie-backend-exam/nginx.conf:/etc/nginx/nginx.conf
    command: [nginx-debug, '-g', 'daemon off;']
    depends_on:
      - inicie-backend
    networks:
      - inicie-network

volumes:
  db_data:

networks:
  inicie-network:
    driver: bridge
